# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[('batchmortal', 'batchmortal'), ('icon.ico', '.')],
    hiddenimports=['main'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide6.QtWebEngine', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets',
              'PySide6.QtWebChannel', 'PySide6.QtWebSockets',
              'PySide6.QtBluetooth', 'PySide6.QtNfc', 'PySide6.QtSensors',
              'PySide6.QtSerialPort', 'PySide6.QtSql', 'PySide6.QtTest',
              'PySide6.QtXml', 'PySide6.QtHelp', 'PySide6.QtLocation',
              'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets',
              'PySide6.QtPositioning', 'PySide6.QtPrintSupport',
              'PySide6.QtQuick', 'PySide6.QtQuickWidgets',
              'PySide6.QtQml', 'PySide6.QtSvg', 'PySide6.QtSvgWidgets',
              'PySide6.Qt3DCore', 'PySide6.Qt3DInput', 'PySide6.Qt3DRender',
              'PySide6.Qt3DAnimation', 'PySide6.Qt3DExtras',
              'PySide6.QtDataVisualization', 'PySide6.QtCharts',
              'PySide6.QtTextToSpeech', 'PySide6.QtVirtualKeyboard',
              'PySide6.QtRemoteObjects', 'PySide6.QtScxml',
              'PySide6.QtStateMachine', 'PySide6.QtDesigner',
              'PySide6.QtUiTools', 'PySide6.QtAxContainer',
              'setuptools', 'pip', 'pkg_resources'],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BatchMortal',
    icon='e:\\hc\\batchmortal-main\\icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
