# ==== Batch Mortal 分析脚本配置文件 ====
# 由 GUI 工具生成

mode: "mj"

mj:
  nickname: ""
  limit: 30
  modes: "12" 

model_tag: "4.1b"
review_language: "zh-CN"
review_ui: "killerducky"
analyze_bad_move_rate: true
headless: true
dry_run: false
save_screenshot: false
save_local_paipu: false
output: "xlsx"
retry: 3
  # proxy: ""
prewarm_standby: false
unsafe_parallel_review: false
plot: "none"
# plot_limit: 50
